### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by jayavanth** [stingergraph/stinger#235]
\<root>/stinger/build/include/stinger_alg/streaming_connected_components.h:14:37: fatal error: stinger_net/stinger_alg.h: No such file or directory

Full build log: https://pastebin.com/UQJ9YAFM

**Comment by ehein6** [comment]
Pretty sure I caused the issue in this commit: https://github.com/stingergraph/stinger/pull/219/commits/b7b821aaf5a41791f2aa385dd1ef205b3280b757

CMake isn't correctly detecting that stinger_net headers need to be generated before stinger_alg gets built. We may need to link against stinger_net again just to make it order things correctly, even though stinger_alg doesn't have any link dependencies.

As a workaround, try building again with `make -k` and then `make` to get it to generate the stinger_net headers first. The Travis build works fine because it happens to pick a different build order. Or add `stinger_net` to the list of libraries in stinger_alg's CMakeLists.txt.

**Comment by jayavanth** [comment]
Adding stinger_net to the CMakeLists.txt fixed it. Thanks!

**Comment by Xia0ben** [comment]
Hello,
Just a small heads up to notify you it would be great if the fix introduced in https://github.com/ehein6/stinger/commit/60cd623c7ffe888fb8616e0ec2c8291800a8e03b that solved this bug were to be merged with the master =).
